### ISSUE TITLE
Local install page is unclear

### ISSUE THREAD

**Issue by ssk2** [dcos/dcos-docs#146]
The title of the local install page is "Install DC/OS on Vagrant" - but from what I can work out, the linked installer in the first script is actually using Docker. 

(It complained when I launched it and Docker wasn't available:)
```
➜  Downloads ./dcos_generate_config.sh
docker should be installed and running. Aborting.
```

Which is it? If it's Docker, we should call this out as a requirement and rename this page's title. 

It would be useful to have a paragraph comparing the two installation methods too.

**Comment by mhausenblas** [comment]
Is this still and issue? If not, let's close …

**Comment by ssk2** [comment]
I figured it out - this was user error. Thanks!

**Comment by mhausenblas** [comment]
I ❤️ layer 8 issues. Thanks @ssk2!

**Comment by brianrusso** [comment]
This is still a problem with the current release.

Solution is to install docker (_apt install docker.io_ on ubuntu), however this is not mentioned in the docs.
