### ISSUE TITLE
How to configure Azure Active Directory with DC/OS

### ISSUE THREAD

**Issue by bmscholl** [dcos/dcos-docs#16]
This walkthrough will cover how to enable AAD authentication for the DC/OS admin router on Azure

**Comment by mhausenblas** [comment]
@bmscholl do you plan to do this? If so, can I ask you to create a new issue on [Jira](https://dcosjira.atlassian.net) since we're migrating over?

**Comment by bmscholl** [comment]
Yes, I'm planning to do this. I'll create a new issue in Jira

**Comment by mhausenblas** [comment]
Thanks a bunch @bmscholl!
