### ISSUE TITLE
How to configure and deploy a containerized microservices application to DC/OS

### ISSUE THREAD

**Issue by bmscholl** [dcos/dcos-docs#17]
Walkthrough for configuring and deploying a containerized microservices application to DC/OS on Azure

**Comment by mhausenblas** [comment]
Same here @bmscholl — do you plan to do this? If so, can I ask you to create a new issue on [Jira](https://dcosjira.atlassian.net) since we're migrating over?

**Comment by bmscholl** [comment]
Yes, I'm planning to do this. I'll create a new issue in Jira

**Comment by mhausenblas** [comment]
… and again, thank you! :)
