### ISSUE TITLE
DC/OS API Design Doc is incomplete

### ISSUE THREAD

**Issue by ssk2** [dcos/dcos-docs#195]
Not sure if this is a WIP still:
https://dcos.io/docs/1.7/overview/design/dcos-api/

This page could be cleaned up and have some detail added.

**Comment by mhausenblas** [comment]
@guenter want to comment on that?

**Comment by mhausenblas** [comment]
This is intentionally WIP, further comments pls via https://dcosjira.atlassian.net/browse/DCOS-78
