### ISSUE TITLE
Zero Downtime Deployments (Marathon)

### ISSUE THREAD

**Issue by aquamatthias** [dcos/dcos-docs#23]
Hierarchy: /administration/upgrade, /usage/service-upgrade
Type: Deep-Dive
Priority: 6

**Comment by mhausenblas** [comment]
@aquamatthias do you plan to do this? If so, can I ask you to create a new issue on [Jira](https://dcosjira.atlassian.net) since we're migrating over?

**Comment by aquamatthias** [comment]
Will create a JIRA for that.
