### ISSUE TITLE
Create /administration/faq

### ISSUE THREAD

**Issue by mhausenblas** [dcos/dcos-docs#234]
Admin FAQ around installing, sizing, monitoring, upgrades

**Comment by mhausenblas** [comment]
Q: Can I install DC/OS on an already running Mesos cluster?

**Comment by JohnOmernik** [comment]
Q: What are the OS requirements of DC/OS.  (At one point, systemd I thought was required, thus Ubuntu 16.04 may be required... will it work with 16.04? Etc.)

**Comment by mhausenblas** [comment]
@JohnOmernik so I guess we should update https://dcos.io/docs/1.7/administration/installing/custom/system-requirements/ as well?

**Comment by JohnOmernik** [comment]
I think so, note my "think" in my previous point, as a non-Mesosphere person, I am basing this on a sales call I had roughly 6 months ago, not on intimate knowledge with the product.

**Comment by JohnOmernik** [comment]
Additional Questions: 
Does DCOS install Zookeeper, or can I use my own Zookeeper quorum?
Is there any interaction/interfacing with Clustered Filesystems like MapR-FS installed on all nodes?  (This is something I'd be working on, but if there people, who may know MapR and Mesos... hint hint @mhausenblas  :) ) Who could provide some recommendations there it would be great.

**Comment by mhausenblas** [comment]
Q: Hi, I'm new in DCOS, I have being reading the documentation and I am not sure what is the function of the boostrap node. At documentation I've read that the bootstrap node is where the installation is run and is a permanent part of the cluster and is required for DC/OS recovery. Once the installation is done, would the boostrap node be necessary only for recovery?

A: Bootstrap node is needed only during the installation. You configure the installation files on this node, these files are provided then to the cluster nodes using an HTTP server which is also running on the bootstrap node. If you are planning to add new nodes to your cluster in the future it would be just convenient to keep the bootstrap node or it's snapshot.

**Comment by activatedgeek** [comment]
Q: Can I deploy DC/OS to an existing Mesos cluster?

**Comment by jgarcia-mesosphere** [comment]
Keep 'em coming!
