### ISSUE TITLE
Image links are broken in spark tutorial

### ISSUE THREAD

**Issue by vinodkone** [dcos/dcos-docs#236]
Image links in this page appear to be broken

https://dcos.io/docs/1.7/usage/tutorials/spark/
![screen shot 2016-04-19 at 10 19 11 am](https://cloud.githubusercontent.com/assets/48131/14648655/319a554c-0618-11e6-955e-d0346c79c968.png)

**Comment by mhausenblas** [comment]
Thanks!

**Comment by mhausenblas** [comment]
Should be fixed now, takes a bit until the website is build and deployed.
