### ISSUE TITLE
DCOS Autoscaling Example Broken Due to Authentication

### ISSUE THREAD

**Issue by gprimeca** [dcos/dcos-docs#237]
I was tying to try out the autoscaling feature from this tutorial:
https://dcos.io/docs/1.7/usage/tutorials/autoscaling/cpu-memory/

The marathon-autoscale.py kept on giving me a stack trace. After digging into the code the http://<dns-hostname>/marathon/v2/apps now requires authentication and therefore this example is broken due to the introduction of authentication in the open source release.

HTTP CODE 401 is returned instead of the expected JSON.

https://github.com/mesosphere/marathon-autoscale/blob/master/marathon-autoscale.py#L25

**Comment by mhausenblas** [comment]
Thanks a lot @gprimeca!

**Comment by mhausenblas** [comment]
Moved it to Jira: https://dcosjira.atlassian.net/browse/DCOS-245
