### ISSUE TITLE
Deprecate and Replace Docker App Tutorial

### ISSUE THREAD

**Issue by gabrielhartmann** [dcos/dcos-docs#240]
https://docs.mesosphere.com/usage/tutorials/docker-app/

This tutorial is broken and at least one user spent a lot of time trying to get it to work.

See this conversation. https://dcos-community.slack.com/archives/general/p1461117000001003

**Comment by mhausenblas** [comment]
Closing. Not dcos.io …

**Comment by gabrielhartmann** [comment]
@sargun What is necessary to get the hello world Docker container speaking outside the cluster in the simplest possible way.  No marathon-lb.
