### ISSUE TITLE
Post-Flight Faild

### ISSUE THREAD

**Issue by Sun-zhe** [dcos/dcos-docs#241]
Hi, folks,

Greeting from me.
I got an error when `Running Rost-Flight`, the agents were completed, but Master was error.
`Environment: RHEL 7.1`
I checked the status:
SSH to master:

> $journactl –u dcos-exhibitor -b

```
-- Logs begin at Tue 2016-04-19 15:38:32 CST, end at Wed 2016-04-20 14:38:16 CST. --
Apr 20 12:40:31 worker02 systemd[1]: Started Exhibitor Zookeeper Supervisor.
Apr 20 12:40:31 worker02 systemd[1]: Starting Exhibitor Zookeeper Supervisor...
Apr 20 12:42:39 worker02 unshare[32443]: curl: (7) Failed to connect to 169.254.169.254 port 80: Connection timed out
Apr 20 12:42:39 worker02 unshare[32443]: inet_aton exited with illegal IP address string passed to inet_aton.  is not a valid IPv4 address
Apr 20 12:42:39 worker02 systemd[1]: dcos-exhibitor.service: main process exited, code=exited, status=1/FAILURE
Apr 20 12:42:39 worker02 systemd[1]: Unit dcos-exhibitor.service entered failed state.
Apr 20 12:42:39 worker02 systemd[1]: dcos-exhibitor.service failed.
Apr 20 12:42:44 worker02 systemd[1]: dcos-exhibitor.service holdoff time over, scheduling restart.
```

> $journactl –u dcos-mesos-master -b

```
-- Logs begin at Tue 2016-04-19 15:38:32 CST, end at Wed 2016-04-20 14:46:38 CST. --
Apr 20 12:40:31 worker02 systemd[1]: Starting Mesos Master...
Apr 20 12:40:31 worker02 exhibitor_wait.py[32438]: Could not get exhibitor status: http://127.0.0.1:8181/exhibitor/v1/cluster/status
Apr 20 12:40:31 worker02 systemd[1]: dcos-mesos-master.service: control process exited, code=exited status=1
Apr 20 12:40:31 worker02 systemd[1]: Failed to start Mesos Master.
Apr 20 12:40:31 worker02 systemd[1]: Unit dcos-mesos-master.service entered failed state.
Apr 20 12:40:31 worker02 systemd[1]: dcos-mesos-master.service failed.
Apr 20 12:40:46 worker02 systemd[1]: dcos-mesos-master.service holdoff time over, scheduling restart.
```

> $journalctl –u dcos-mesos-dns -b

```
Apr 20 12:41:00 worker02 mesos-dns[32467]: 2016/04/20 12:41:00 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: getsockopt: connection refused
Apr 20 12:41:01 worker02 mesos-dns[32467]: ERROR: 2016/04/20 12:41:01 main.go:80: master detection timed out after 30s
Apr 20 12:41:01 worker02 systemd[1]: dcos-mesos-dns.service: main process exited, code=exited, status=1/FAILURE
Apr 20 12:41:01 worker02 systemd[1]: Unit dcos-mesos-dns.service entered failed state.
Apr 20 12:41:01 worker02 systemd[1]: dcos-mesos-dns.service failed.
Apr 20 12:41:06 worker02 systemd[1]: dcos-mesos-dns.service holdoff time over, scheduling restart.
```

> $journalctl –u dcos-marathon -b

```
-- Logs begin at Tue 2016-04-19 15:38:32 CST, end at Wed 2016-04-20 14:50:30 CST. --
Apr 20 12:40:31 worker02 systemd[1]: Starting Marathon...
Apr 20 12:40:31 worker02 exhibitor_wait.py[32476]: Could not get exhibitor status: http://127.0.0.1:8181/exhibitor/v1/cluster/status
Apr 20 12:40:32 worker02 systemd[1]: dcos-marathon.service: control process exited, code=exited status=1
Apr 20 12:40:32 worker02 systemd[1]: Failed to start Marathon.
Apr 20 12:40:32 worker02 systemd[1]: Unit dcos-marathon.service entered failed state.
Apr 20 12:40:32 worker02 systemd[1]: dcos-marathon.service failed.
Apr 20 12:40:47 worker02 systemd[1]: dcos-marathon.service holdoff time over, scheduling restart.
```

> $journalctl –u dcos-nginx -b

```
-- Logs begin at Tue 2016-04-19 15:38:32 CST, end at Wed 2016-04-20 14:51:49 CST. --
Apr 20 12:40:31 worker02 systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 20 12:40:31 worker02 curl[32468]: curl: (7) Failed to connect to localhost port 8101: Connection refused
Apr 20 12:40:31 worker02 systemd[1]: dcos-nginx.service: control process exited, code=exited status=7
Apr 20 12:40:31 worker02 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Apr 20 12:40:31 worker02 systemd[1]: Unit dcos-nginx.service entered failed state.
Apr 20 12:40:31 worker02 systemd[1]: dcos-nginx.service failed.
Apr 20 12:40:36 worker02 systemd[1]: dcos-nginx.service holdoff time over, scheduling restart.
```

> $journalctl –u dcos-gen-resolvconf -b

```
-- Logs begin at Tue 2016-04-19 15:38:32 CST, end at Wed 2016-04-20 14:53:15 CST. --
Apr 20 12:40:31 worker02 systemd[1]: Started Update systemd-resolved for mesos-dns.
Apr 20 12:40:31 worker02 systemd[1]: Starting Update systemd-resolved for mesos-dns...
Apr 20 12:40:36 worker02 gen_resolvconf.py[32439]: Skipping DNS server 15.242.100.56: no response
Apr 20 12:41:32 worker02 systemd[1]: Started Update systemd-resolved for mesos-dns.
Apr 20 12:42:44 worker02 gen_resolvconf.py[32439]: curl: (7) Failed to connect to 169.254.169.254 port 80: Connection timed out
Apr 20 12:42:44 worker02 gen_resolvconf.py[32439]: inet_aton exited with illegal IP address string passed to inet_aton.  is not a valid IPv4 address
Apr 20 12:42:44 worker02 systemd[1]: dcos-gen-resolvconf.service: main process exited, code=exited, status=1/FAILURE
Apr 20 12:42:44 worker02 systemd[1]: Unit dcos-gen-resolvconf.service entered failed state.
Apr 20 12:42:44 worker02 systemd[1]: dcos-gen-resolvconf.service failed.
```

And when SSH to agent :

> $journalctl –u dcos-mesos-slave -b

```
-- Logs begin at Tue 2016-04-19 15:32:51 CST, end at Wed 2016-04-20 14:55:23 CST. --
Apr 20 13:06:50 worker03 systemd[1]: Starting Mesos Slave...
Apr 20 13:06:51 worker03 ping[14893]: ping: unknown host leader.mesos
Apr 20 13:06:51 worker03 systemd[1]: dcos-mesos-slave.service: control process exited, code=exited status=2
Apr 20 13:06:51 worker03 systemd[1]: Failed to start Mesos Slave.
Apr 20 13:06:51 worker03 systemd[1]: Unit dcos-mesos-slave.service entered failed state.
Apr 20 13:06:51 worker03 systemd[1]: dcos-mesos-slave.service failed.
Apr 20 13:06:56 worker03 systemd[1]: dcos-mesos-slave.service holdoff time over, scheduling restart.

```
I don’t what’s going on. Do you have any idear? Thank you very much!

**Comment by cmaloney** [comment]
This sort of bug should be submitted in the [DCOS JIRA](https://dcosjira.atlassian.net).

The issue here is that your ip-detect script output an invalid IPv4 address. In particular, it seems to have output an empty string based on:
`Apr 20 12:42:44 worker02 gen_resolvconf.py[32439]: inet_aton exited with illegal IP address string passed to inet_aton.  is not a valid IPv4 address`.

The IP Detect script needs to be identical / the same on every host. It needs to return a single IPv4 address which is the IP address all services on the machine should listen to. There is more documentation about ip-detect scripts and examples inside the doc: https://dcos.io/docs/1.7/administration/installing/custom/advanced/

**Comment by imTachu** [comment]
This is happening to me too, my setup configuration was very simple. I don't see the issue in JIRA, I don't know if it was created or solved or anything. What can be done? 
![image](https://cloud.githubusercontent.com/assets/2230140/17079894/8071bab4-50e3-11e6-8d78-7114a8a42d41.png)

**Comment by sauravsuman689** [comment]
I am getting below error. Please advise.

$journactl –u dcos-exhibitor -b

localhost.localdomain systemd[1]: dcos-exhibitor.service: main process exited, code=exited, status=1/FAILURE
Dec 21 05:02:59 localhost.localdomain systemd[1]: Unit dcos-exhibitor.service entered failed state.
Dec 21 05:02:59 localhost.localdomain systemd[1]: dcos-exhibitor.service failed.
Dec 21 05:03:04 localhost.localdomain systemd[1]: dcos-exhibitor.service holdoff time over, scheduling restart.
Dec 21 05:03:04 localhost.localdomain systemd[1]: Started Exhibitor: Zookeeper Supervisor Service.
Dec 21 05:03:04 localhost.localdomain systemd[1]: Starting Exhibitor: Zookeeper Supervisor Service...
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: Traceback (most recent call last):
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/exhibitor--894b6beb2ab46448cec50a59712ad6c3dd
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: detected_ip = invoke_detect_ip()
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/exhibitor--894b6beb2ab46448cec50a59712ad6c3dd
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: ['/opt/mesosphere/bin/detect_ip']).strip().decode('utf-8')
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: **kwargs).stdout
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: with Popen(*popenargs, **kwargs) as process:
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: restore_signals, start_new_session)
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: raise child_exception_type(errno_num, err_msg)
Dec 21 05:03:04 localhost.localdomain start_exhibitor.py[6182]: OSError: [Errno 8] Exec format error
