### ISSUE TITLE
Page appears to be blank

### ISSUE THREAD

**Issue by faddat** [dcos/dcos-docs#243]
The page on cluster resources seems blank :).

**Comment by mhausenblas** [comment]
What URL are your talking about @faddat?

**Comment by mohitsoni** [comment]
@mhausenblas: https://dcos.io/docs/1.7/administration/cluster-size/

**Comment by mhausenblas** [comment]
Got it and thanks @mohitsoni—that's covered by #233 and hence a dupe, closing …
