### ISSUE TITLE
bugs in documentation

### ISSUE THREAD

**Issue by ghost** [dcos/dcos-docs#245]
Hi there are some bugs in your documentation for the CLI install.

1) SSH_KEY_PATH variable in the config.yaml seems to be ignored, or if present, for some reason the process cannot find the file?

I can provide more detailed feedback onceI try the installation again, but i think it would be better to use ansible for the installation rather then a bash script.

Kashif

**Issue tracking is moving to the [DCOS JIRA](https://dcosjira.atlassian.net/) ([dcos-docs component](https://dcosjira.atlassian.net/issues/?jql=project%20%3D%20DCOS%20AND%20component%20%3D%20dcos-docs)).
Issues on Github will be disabled soon, but can't be disabled until existing ones are migrated. So please make a JIRA issue instead!**

**Comment by pyronicide** [comment]
@malnick Any ideas?

**Comment by mhausenblas** [comment]
@pyronicide unsure if this is still relevant. Propose to close this (and if it's relevant to re-open on Jira)

**Comment by jibsonline** [comment]
Its the case sensitivity issue. SSH_KEY_PATH  has to be ssh_key_path.

**Comment by LoboHacks** [comment]
$ sudo mkdir -p /etc/systemd/system/docker.service.d && sudo tee /etc/systemd/system/docker.service.d/override.conf <<- EOF
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
EOF

Does not work on CentOS 7.2

Fix: Delete -H fd:// ???

Cheers

**Comment by gbrian** [comment]
Thanks @LoboHacks found same issue and followed: https://github.com/docker/docker/issues/22847

**Comment by mhausenblas** [comment]
Transferred this one to https://dcosjira.atlassian.net/browse/DCOS-583 and closing it now
