### ISSUE TITLE
I need to know the environment variable that tells a docker host its own mesos dns hostname

### ISSUE THREAD

**Issue by rjurney** [dcos/dcos-docs#246]
**Issue tracking is moving to the [DCOS JIRA](https://dcosjira.atlassian.net/) ([dcos-docs component](https://dcosjira.atlassian.net/issues/?jql=project%20%3D%20DCOS%20AND%20component%20%3D%20dcos-docs)).
Issues on Github will be disabled soon, but can't be disabled until existing ones are migrated. So please make a JIRA issue instead!**

**Comment by ssk2** [comment]
Hi @rjurney, there's no exact environment variable for the Mesos DNS hostname but, assuming you're running your application using Marathon, you can use the variables it provides to get the DNS hostname:
https://mesosphere.github.io/marathon/docs/task-environment-vars.html

**Comment by ssk2** [comment]
I think something like `$MESOS_TASK_ID._tcp.marathon.mesos` would work - although you would need to truncate the task ID to 24 characters (see http://mesosphere.github.io/mesos-dns/docs/naming.html for the constraints).

**Comment by ssk2** [comment]
@jdef, @sargun - can you confirm this?

**Comment by rjurney** [comment]
Ok, I will try this:

`echo ${MESOS_TASK_ID}|cut -c -24`._tcp.marathon.mesos`

On Thu, Apr 21, 2016 at 1:48 PM, Sunil Shah <notifications@github.com>
wrote:

> @jdef <https://github.com/jdef>, @sargun <https://github.com/sargun> -
> can you confirm this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dcos/dcos-docs/issues/246#issuecomment-213107927>
>



-- 
Russell Jurney twitter.com/rjurney russell.jurney@gmail.com relato.io

**Comment by jdef** [comment]
that's not guaranteed to work. mesos-dns also translates "special" characters to a dash `-` so you'd need to do something similar. see the algorithm here: https://github.com/mesosphere/mesos-dns/blob/master/records/labels/labels.go

also 24 chars sounds short - the default is actually 63 (RFC1123).

**Comment by rjurney** [comment]
What worked is the $HOST variable, which sargun told me about :) A host
knows its own mesos dns hostname, which is great!

On Tue, Apr 26, 2016 at 3:32 AM, James DeFelice <notifications@github.com>
wrote:

> that's not guaranteed to work. mesos-dns also translates "special"
> characters to a dash - so you'd need to do something similar. see the
> algorithm here:
> https://github.com/mesosphere/mesos-dns/blob/master/records/labels/labels.go
>
> also 24 chars sounds short - the default is actually 63 (RFC1123).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dcos/dcos-docs/issues/246#issuecomment-214696975>
>



-- 
Russell Jurney twitter.com/rjurney russell.jurney@gmail.com relato.io

**Comment by mhausenblas** [comment]
Seems this has been resolved. If not, please continue on Jira: https://dcosjira.atlassian.net
