### ISSUE TITLE
Download packages 403 Forbidden

### ISSUE THREAD

**Issue by hbombonato** [dcos/dcos-docs#260]
Hello Folx,

   I try install dcos with UI and process never is done, when check the internet access I looked this problem. Can you check please if is true?

curl  https://downloads.dcos.io/dcos/stable/packages/3dt/3dt--c3970af261c1e9ed9014904a6408617dafd41e6c.tar.xz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>642C6FB052E7C6B0</RequestId><HostId>ArQbwFezRMVMC+eGUHZcROZwiPWigE0JudvJ2PoeqwryDsNqL6UIbtqrvnOzvtzBfkuJTub63jA=</HostId></Error>cin_hbombonato@ni-88654-7:ed9014904a6408617dafd41e6c.tar.xzads.dcos.io/dcos/stable/packages/3dt/3dt--c3970af261c1e9e
cin_hbombonato@ni-88654-7:~/Downloads$ curl -fLsSv  https://downloads.dcos.io/dcos/stable/packages/3dt/3dt--c3970af261c1e9ed9014904a6408617dafd41e6c.tar.xz
*   Trying 54.192.163.77...
* Connected to downloads.dcos.io (54.192.163.77) port 443 (#0)
* found 175 certificates in /etc/ssl/certs/ca-certificates.crt
* found 712 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.dcos.io (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=San Francisco,O=Mesosphere\, Inc.,CN=*.dcos.io
* 	 start date: Fri, 08 Apr 2016 00:00:00 GMT
* 	 expire date: Wed, 17 Apr 2019 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /dcos/stable/packages/3dt/3dt--c3970af261c1e9ed9014904a6408617dafd41e6c.tar.xz HTTP/1.1
> Host: downloads.dcos.io
> User-Agent: curl/7.43.0
> Accept: */*
> 
* The requested URL returned error: 403 Forbidden
* Closing connection 0
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by mhausenblas** [comment]
Do you still have this issue? If so, please raise at Jira: https://dcosjira.atlassian.net
