### ISSUE TITLE
dcos-nginx service not found 

### ISSUE THREAD

**Issue by naphthalene** [dcos/dcos-docs#278]
**Issue tracking is moving to the [DCOS JIRA](https://dcosjira.atlassian.net/) ([dcos-docs component](https://dcosjira.atlassian.net/issues/?jql=project%20%3D%20DCOS%20AND%20component%20%3D%20dcos-docs)).
Issues on Github will be disabled soon, but can't be disabled until existing ones are migrated. So please make a JIRA issue instead!**

Successfully starts:

```
Creating directories under /etc/mesosphere
Creating role file for master
Configuring DC/OS
Setting and starting DC/OS
```

```
ubuntu@master:/tmp/dcos$ sudo systemctl start dcos-nginx
Failed to start dcos-nginx.service: Unit dcos-nginx.service failed to load: No such file or directory.
```
I am unable to access port 80 on the (singular) master node.

**Comment by mhausenblas** [comment]
@naphthalene this sounds like a problem with the software, not directly docs related. Also, note that you shouldn't be raising issues here anymore but only in Jira. Can you please report it here: https://dcosjira.atlassian.net

**Comment by naphthalene** [comment]
I have opened an issue on the tracker, didn't realize there was a migration to Jira when I made the ticket
