### ISSUE TITLE
Error in Installation guide for Azure

### ISSUE THREAD

**Issue by waitingkuo** [dcos/dcos-docs#298]
in <https://dcos.io/docs/1.7/administration/installing/cloud/azure/>

    # Connect to master node with ssh
    $ ssh -p2200 azureuser@MASTER_LOAD_BALANCER -L 8000:localhost:80

    # Install virtualenv
    $ sudo apt-get -y install virtualenv

    # Install CLI on the master node and configure with http://localhost
    $ mkdir -p dcos && cd dcos &&
    $ curl -O https://downloads.dcos.io/dcos-cli/install-optout.sh && \
       bash ./install-optout.sh . http://localhost && \
       source ./bin/env-setup

    # Now you can use the DC/OS CLI:
    $ dcos package search

# should modifiy 

    $ curl -O https://downloads.dcos.io/dcos-cli/install-optout.sh && \
       bash ./install-optout.sh . http://localhost && \
       source ./bin/env-setup

as

    $ curl -O https://downloads.dcos.io/dcos-cli/install-optout.sh && \
       bash ./install-optout.sh . http://localhost:8000 && \
       source ./bin/env-setup

since the local port for the ssh tunnel is 8000

**Comment by mhausenblas** [comment]
Great catch @waitingkuo! Would you like to send in a PR to fix this yourself? BTW, we're in the process of moving all the issues to [DCOS JIRA](https://dcosjira.atlassian.net/) so appreciate it if you'd, going forward, raise an issue there ;)

**Comment by mhausenblas** [comment]
Moved to Jira, see https://dcosjira.atlassian.net/browse/DCOS-152
