### ISSUE TITLE
 tomcat status always is "waiting".

### ISSUE THREAD

**Issue by samsha1971** [dcos/dcos-docs#355]
in "https://dcos.io/docs/1.7/usage/tutorials/tomcat/#run-the-container",

run "curl -O https://dcos.io/docs/1.7/usage/tutorials/tomcat/marathon.json"
run "dcos marathon app add marathon.json ",
but tomcat application status always is "waiting".

Temporary solution :
change : "hostPort": 0,
and remove:
 "acceptedResourceRoles": [
    "slave_public"
  ]

What's wrong?
Is a document or DCOS errors?

**Comment by mhausenblas** [comment]
@samsha1971 thanks for bringing this to our attention! Can I ask you to raise the issue on Jira https://dcosjira.atlassian.net please since we're not using the issue tracker here anymore? I'll have a look into it then …
