### ISSUE TITLE
final step has incorrect port

### ISSUE THREAD

**Issue by tudor-james** [dcos/dcos-docs#381]
**Issue tracking is moving to the [DCOS JIRA](https://dcosjira.atlassian.net/) ([dcos-docs component](https://dcosjira.atlassian.net/issues/?jql=project%20%3D%20DCOS%20AND%20component%20%3D%20dcos-docs)).
Issues on Github will be disabled soon, but can't be disabled until existing ones are migrated. So please make a JIRA issue instead!**

https://dcos.io/docs/1.7/administration/installing/custom/advanced/

Last step needs port 8080 adding.  Couldn't raise in Jira as it needs a 'Reporter' but the field wasn't available.

**Comment by jgarcia-mesosphere** [comment]
Hello! The instruction:

> Launch the DC/OS web interface at: `http://<master-node-public-ip>/`. If this doesn’t work, take a look at the troubleshooting docs

will only work if the user points their browser at port `:80`. If the user uses port `:8080` instead, this will be blocked as port `:8080` is not outside the cluster in DC/OS.

I'll close this issue.

**Comment by tudor-james** [comment]
I followed the instructions and I have nothing on the master on port 80, only 8080, which is accessible from outside the cluster.  I get the Marathon interface.

**Comment by jgarcia-mesosphere** [comment]
Hi! In that case, it sounds like `dcos-adminrouter` or `dcos-nginx` are not functioning correctly.

**Comment by tudor-james** [comment]
Bullseye!

Failed Units: 4
  dcos-adminrouter-reload.service
  dcos-gen-resolvconf.service
  dcos-logrotate.service
  dcos-spartan-watchdog.servi

I'll debug..

**Comment by jgarcia-mesosphere** [comment]
Would like to catch up with you at chat.dcos.io if you'd like to dig in.

**Comment by tudor-james** [comment]
I'm going to call it a day now but I'll be available tomorrow if you are free?
