### ISSUE TITLE
How to run Spark jobs that connect to Cassandra nodes on DCOS

### ISSUE THREAD

**Issue by cornelf** [dcos/dcos-docs#4]

**Comment by mhausenblas** [comment]
@cornelf do you plan to do this? If so, can I ask you to create a new issue on [Jira](https://dcosjira.atlassian.net) since we're migrating over?

**Comment by mhausenblas** [comment]
Closing now. If you still plan to do it, please raise a new issue in [Jira](https://dcosjira.atlassian.net/) using the `documentation` component.
