### ISSUE TITLE
Error showing up after installing DC/OS 1.7 with Vagrant 

### ISSUE THREAD

**Issue by usultrared** [dcos/dcos-docs#62]
==> m1:       DCOS Unhealthy
==> m1:       [dcos-signal.service]: DCOS Telemetry and Tracking Service dcos-signal.service state is not one of the possible states [active inactive activating]. Current state is [ failed ]. Please check `systemctl show all dcos-signal.service` to check current unit state. 
==> m1:       -- Logs begin at Tue 2016-04-12 20:57:30 PDT, end at Tue 2016-04-12 21:20:22 PDT. --
==> m1:       Apr 12 21:04:14 m1.dcos systemd[1]: Starting Signal: DCOS Telemetry and Tracking Service...
==> m1:       Apr 12 21:04:14 m1.dcos systemd[1]: dcos-signal.service: control process exited, code=exited status=1
==> m1:       Apr 12 21:04:14 m1.dcos systemd[1]: Failed to start Signal: DCOS Telemetry and Tracking Service.
==> m1:       Apr 12 21:04:14 m1.dcos systemd[1]: Unit dcos-signal.service entered failed state.
==> m1:       Apr 12 21:04:14 m1.dcos systemd[1]: dcos-signal.service failed.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/opt/mesosphere/bin/postflight.sh

Stdout from the command:

Stderr from the command:

DCOS Unhealthy
[dcos-signal.service]: DCOS Telemetry and Tracking Service dcos-signal.service state is not one of the possible states [active inactive activating]. Current state is [ failed ]. Please check `systemctl show all dcos-signal.service` to check current unit state. 
-- Logs begin at Tue 2016-04-12 20:57:30 PDT, end at Tue 2016-04-12 21:20:22 PDT. --
Apr 12 21:04:14 m1.dcos systemd[1]: Starting Signal: DCOS Telemetry and Tracking Service...
Apr 12 21:04:14 m1.dcos systemd[1]: dcos-signal.service: control process exited, code=exited status=1
Apr 12 21:04:14 m1.dcos systemd[1]: Failed to start Signal: DCOS Telemetry and Tracking Service.
Apr 12 21:04:14 m1.dcos systemd[1]: Unit dcos-signal.service entered failed state.
Apr 12 21:04:14 m1.dcos systemd[1]: dcos-signal.service failed.

**Comment by karlkfi** [comment]
Is this repeatable? does it happen after you destroy (`vagrant destroy -f`) and recreate your cluster?

In the future please post dcos-vagrant questions on JIRA tagged with the dcos-vagrant component: https://dcosjira.atlassian.net/projects/DCOS

**Comment by karlkfi** [comment]
Vagrant issues should be raised on JIRA. Closing.
