### ISSUE TITLE
Failed to extend node using Vagrant command

### ISSUE THREAD

**Issue by usultrared** [dcos/dcos-docs#64]
Guys, 
I am trying to extend one node using the below steps:
1.  Modify the following file 
ams-MacBook-Pro:dcos-vagrant samchen$ more VagrantConfig.yaml
m1:
 ip: 192.168.65.90
 cpus: 2
 memory: 1024
 type: master
a1:
 ip: 192.168.65.111
 cpus: 2
 memory: 1024
 type: agent-private
a2:
 ip: 192.168.65.112
 cpus: 2
 memory: 2048
 type: agent-private
p1:
 ip: 192.168.65.60
 cpus: 2
 memory: 1024
 type: agent-public
 aliases:
 - spring.acme.org
 - oinker.acme.org
boot:
 ip: 192.168.65.50
 cpus: 2
 memory: 256

2. Using Vagrant up a2

The consequence log here 
bash-3.2$ vagrant up a2
Bringing machine 'a2' up with 'virtualbox' provider...
==> a2: Importing base box 'mesosphere/dcos-centos-virtualbox'...
==> a2: Matching MAC address for NAT networking...
==> a2: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> a2: Setting the name of the VM: a2.dcos
==> a2: Fixed port collision for 22 => 2222. Now on port 2203.
==> a2: Clearing any previously set network interfaces...
==> a2: Preparing network interfaces based on configuration...
    a2: Adapter 1: nat
    a2: Adapter 2: hostonly
==> a2: Forwarding ports...
    a2: 22 (guest) => 2203 (host) (adapter 1)
==> a2: Running 'pre-boot' VM customizations...
==> a2: Booting VM...
==> a2: Waiting for machine to boot. This may take a few minutes...
    a2: SSH address: 127.0.0.1:2203
    a2: SSH username: vagrant
    a2: SSH auth method: private key
    a2: Warning: Remote connection disconnect. Retrying...
    a2: 
    a2: Vagrant insecure key detected. Vagrant will automatically replace
    a2: this with a newly generated keypair for better security.
    a2: 
    a2: Inserting generated public key within guest...
    a2: Removing insecure key from the guest if it's present...
    a2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> a2: Machine booted and ready!
==> a2: Checking for guest additions in VM...
==> a2: Setting hostname...
==> a2: Configuring and enabling network interfaces...
==> a2: Mounting shared folders...
    a2: /vagrant => /Users/samchen/dcos-vagrant
==> a2: Updating /etc/hosts file on active guest machines...

==> a2: Updating /etc/hosts file on host machine (password may be required)...
Password:
Sorry, try again.
Password:
==> a2: Running provisioner: dcos_ssh...
    host: Found existing keys
==> a2: Inserting generated public key within guest...
==> a2: Configuring vagrant to connect using generated private key...
==> a2: Removing insecure key from the guest, if it's present...
==> a2: Running provisioner: shell...
    a2: Running: script: Certificate Authorities
==> a2: >>> Installing Certificate Authorities

When I check the node in http://m1.dcos. There are nothing showing up related to a2

**Comment by karlkfi** [comment]
dcos-vagrant does not currently support re-provisioning or resizing the cluster. This is because the boot node performs a full install of dcos onto nodes that exist when it comes up. 

It may be possible to manually install dcos on the new node, but it's not currently automatic.

https://github.com/dcos/dcos-vagrant/blob/master/lib/vagrant-dcos/provisioner.rb#L142

For future dcos-vagrant issues, please raise issues on DCOS JIRA tagged with the dcos-vagrant component: https://dcosjira.atlassian.net/projects/DCOS
