### ISSUE TITLE
Add local set up instructions to contributor guidelines

### ISSUE THREAD

**Issue by ssk2** [dcos/dcos-docs#94]
As someone creating docs, I'd love to render them locally to see if the formatting is correct _before_ submitting my pull request. We should add instructions for this to the contributor guidelines.

**Comment by mhausenblas** [comment]
This has been addressed in https://github.com/dcos/dcos-docs/blob/master/README.md and https://github.com/dcos/dcos-docs/blob/master/CONTRIBUTING.md
